- name: Install 1Password on Debian/Ubuntu and Fedora
  hosts: localhost
  become: yes
  tasks:
    - name: Detect the operating system
      ansible.builtin.shell: cat /etc/os-release | grep -w ID | cut -d '=' -f 2
      register: os_type
      changed_when: false
    - name: Install 1Password and 1Password CLI on Fedora
      when: os_type.stdout == "fedora"
      block:
        - name: Add the key for 1Password
          ansible.builtin.shell:
            cmd: sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
        - name: Add the 1Password YUM repository
          ansible.builtin.shell:
            cmd: sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
        - name: Install 1Password and 1Password CLI
          ansible.builtin.dnf:
            name:
              - 1password
              - 1password-cli
            state: present
            update_cache: yes
        - name: Verify 1Password CLI installation
          ansible.builtin.command:
            cmd: op --version
          register: op_version
          failed_when: op_version.rc != 0
        - name: Display 1Password CLI version
          ansible.builtin.debug:
            msg: "1Password CLI installed successfully on Fedora: {{ op_version.stdout }}"
    - name: Install 1Password and 1Password CLI on Debian/Ubuntu
      when: os_type.stdout in ["debian", "ubuntu"]
      block:
        - name: Add the key for the 1Password apt repository
          ansible.builtin.shell:
            cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/keyrings/1password-archive-keyring.gpg
        - name: Add the 1Password apt repository
          ansible.builtin.lineinfile:
            path: /etc/apt/sources.list.d/1password.list
            line: 'deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main'
            create: yes
        - name: Add the debsig-verify policy
          block:
            - name: Create debsig-verify policy directory
              ansible.builtin.file:
                path: /etc/debsig/policies/AC2D62742012EA22/
                state: directory
            - name: Download debsig-verify policy for 1Password
              ansible.builtin.get_url:
                url: https://downloads.1password.com/linux/debian/debsig/1password.pol
                dest: /etc/debsig/policies/AC2D62742012EA22/1password.pol
            - name: Create debsig keyring directory
              ansible.builtin.file:
                path: /usr/share/debsig/keyrings/AC2D62742012EA22
                state: directory
            - name: Download debsig keyring for 1Password
              ansible.builtin.shell:
                cmd: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --dearmor --output /usr/share/debsig/keyrings/AC2D62742012EA22/debsig.gpg
        - name: Update apt and install 1Password
          ansible.builtin.apt:
            update_cache: yes
            name: 1password
            state: present
        - name: Update apt and install 1Password CLI
          ansible.builtin.apt:
            update_cache: yes
            name: 1password-cli
            state: present
          tags: cli
        - name: Verify 1Password CLI installation
          ansible.builtin.command:
            cmd: op --version
          register: op_version
          failed_when: op_version.rc != 0
          tags: cli
        - name: Display 1Password CLI version
          ansible.builtin.debug:
            msg: "1Password CLI installed successfully on Ubuntu/Debian: {{ op_version.stdout }}"
          tags: cli
