- name: Setup Alpaca, Flatpak, and selected models
  hosts: localhost
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
    - name: Install prerequisites
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - flatpak
        - python3
        - python3-pip
    - name: Add Flathub repository for Flatpak
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      args:
        creates: /var/lib/flatpak/repo/flathub.flatpakrepo
    - name: Install Alpaca using Flatpak
      flatpak:
        name: com.jeffser.Alpaca
        state: present
        remote: flathub
    - name: Install Python dependencies for model handling
      pip:
        name:
          - transformers
          - torch
        state: present
    - name: Install Medllama2 model
      command: flatpak run com.jeffser.Alpaca install Medllama2
      args:
        creates: ~/.alpaca/Medllama2
    - name: Install Llama3.2 model
      command: flatpak run com.jeffser.Alpaca install Llama3.2
      args:
        creates: ~/.alpaca/Llama3.2
    - name: Install Gemma2 model
      command: flatpak run com.jeffser.Alpaca install Gemma2
      args:
        creates: ~/.alpaca/Gemma2
