- name: Install Firefox on Debian-based systems
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Ensure wget is installed
      apt:
        name: wget
        state: present
    - name: Create directory for APT repository keys
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
    - name: Download and store the Mozilla APT repository signing key
      get_url:
        url: https://packages.mozilla.org/apt/repo-signing-key.gpg
        dest: /etc/apt/keyrings/packages.mozilla.org.asc
    - name: Add the Mozilla repository to APT sources
      copy:
        dest: /etc/apt/sources.list.d/mozilla.list
        content: deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main
        mode: '0644'
    - name: Set pin preference for Mozilla packages
      copy:
        dest: /etc/apt/preferences.d/mozilla
        content: |
          Package: *
          Pin: origin packages.mozilla.org
          Pin-Priority: 1000
    - name: Update APT package list
      apt:
        update_cache: yes
    - name: Remove any existing versions of Firefox
      apt:
        name: firefox
        state: absent
        purge: yes
    - name: Install the latest version of Firefox
      apt:
        name: firefox
        state: latest
    - name: Verify Firefox installation
      command: firefox --version
      register: firefox_version_output
    - name: Show installed Firefox version
      debug:
        msg: "Installed Firefox version: {{ firefox_version_output.stdout }}"
