- name: Install detect-secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Install Python3-venv
      ansible.builtin.apt:
        name: python3-venv
        state: present
    - name: Create a virtual environment named 'secrets'
      ansible.builtin.command:
        cmd: python3 -m venv ~/virtual_environments/secrets
        creates: ~/virtual_environments/secrets/bin/activate
      args:
        creates: ~/virtual_environments/secrets
    - name: Install detect-secrets within the virtual environment
      ansible.builtin.pip:
        name: detect-secrets
        state: latest
        virtualenv: ~/virtual_environments/secrets
        virtualenv_command: python3 -m venv
    - name: Install gibberish_detector within the virtual environment
      ansible.builtin.pip:
        name: gibberish_detector
        state: latest
        virtualenv: ~/virtual_environments/secrets
        virtualenv_command: python3 -m venv
    - name: Install checkov
      ansible.builtin.pip:
        name: checkov
        state: latest
        virtualenv: ~/virtual_environments/secrets
        virtualenv_command: python3 -m venv
    - name: Check if gitleaks is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/gitleaks
      register: gitleaks_bin
      tags: ["gitleaks"]
    - name: Download gitleaks binary tar.gz
      ansible.builtin.get_url:
        url: https://github.com/gitleaks/gitleaks/releases/download/v8.23.1/gitleaks_8.23.1_linux_x64.tar.gz
        dest: "/tmp/gitleaks_8.23.1_linux_x64.tar.gz"
        mode: '0644'
      when: gitleaks_bin.stat.exists == false
      tags: ["gitleaks"]
    - name: Extract gitleaks tar.gz
      ansible.builtin.unarchive:
        src: "/tmp/gitleaks_8.23.1_linux_x64.tar.gz"
        dest: "/tmp/"
        remote_src: yes
        creates: "/tmp/gitleaks"
      when: gitleaks_bin.stat.exists == false
      tags: ["gitleaks"]
    - name: Move gitleaks to /usr/local/bin
      become: yes
      ansible.builtin.copy:
        src: "/tmp/gitleaks"
        dest: "/usr/local/bin/gitleaks"
        mode: '0755'
        remote_src: yes
      when: gitleaks_bin.stat.exists == false
      tags: ["gitleaks"]
    - name: Generate Gitleaks completion script for Zsh
      ansible.builtin.command:
        cmd: gitleaks completion zsh
      register: gitleaks_completion_output
    - name: Ensure custom completions directory exists
      ansible.builtin.file:
        path: ~/.oh-my-zsh/custom/completions
        state: directory
        mode: '0755'
    - name: Write Gitleaks completion script to file
      ansible.builtin.copy:
        content: "{{ gitleaks_completion_output.stdout }}"
        dest: ~/.oh-my-zsh/custom/completions/_gitleaks
        mode: '0644'
