- name: Install AWS SAM CLI on Ubuntu
  hosts: localhost
  become: yes
  tasks:
    # - name: Update apt package list
    #   apt:
    #     update_cache: yes

    # - name: Install dependencies (Python3, pip, and unzip)
    #   apt:
    #     name:
    #       - python3
    #       - python3-pip
    #       - unzip
    #     state: present
    - name: Create directory for SAM installation
      file:
        path: /tmp/sam-installation
        state: directory
    - name: Download AWS SAM CLI zip
      get_url:
        url: https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
        dest: /tmp/aws-sam-cli.zip
    - name: Unzip AWS SAM CLI
      unarchive:
        src: /tmp/aws-sam-cli.zip
        dest: /tmp/sam-installation
        remote_src: yes
    - name: Install AWS SAM CLI
      command: /tmp/sam-installation/install
    - name: Verify AWS SAM CLI installation
      command: sam --version
      register: sam_version
    - name: Show AWS SAM CLI version
      debug:
        msg: "Installed AWS SAM CLI version: {{ sam_version.stdout }}"
    - name: Clean up installation files
      file:
        path: /tmp/aws-sam-cli.zip
        state: absent
    - name: Clean up SAM installation directory
      file:
        path: /tmp/sam-installation
        state: absent
