- name: Install SOPS
  hosts: localhost
  become: yes
  vars:
    sops_ubuntu_url: "https://github.com/getsops/sops/releases/download/v3.9.3/sops_3.9.3_amd64.deb"
    sops_ubuntu_package: "sops_3.9.1_amd64.deb"
    sops_fedora_url: "https://github.com/getsops/sops/releases/download/v3.9.3/sops-3.9.3-1.x86_64.rpm"
    sops_fedora_package: "sops-3.9.1-1.x86_64.rpm"
  tasks:
    - name: Determine the distribution
      command: cat /etc/os-release
      register: distro_info
    - name: Set SOPS download URL and package for Ubuntu and Kali
      set_fact:
        sops_url: "{{ sops_ubuntu_url }}"
        sops_package: "{{ sops_ubuntu_package }}"
      when: "'ubuntu' in distro_info.stdout or 'kali' in distro_info.stdout"
    - name: Set SOPS download URL and package for Fedora
      set_fact:
        sops_url: "{{ sops_fedora_url }}"
        sops_package: "{{ sops_fedora_package }}"
      when: "'fedora' in distro_info.stdout"
    - name: Download SOPS package
      ansible.builtin.get_url:
        url: "{{ sops_url }}"
        dest: "/tmp/{{ sops_package }}"
        mode: '0644'
    - name: Install SOPS package on Ubuntu and Kali
      ansible.builtin.apt:
        deb: "/tmp/{{ sops_package }}"
        state: present
      when: "'ubuntu' in distro_info.stdout or 'kali' in distro_info.stdout"
    - name: Install SOPS package on Fedora
      ansible.builtin.dnf:
        name: "/tmp/{{ sops_package }}"
        state: present
        disable_gpg_check: yes
      when: "'fedora' in distro_info.stdout"
    - name: Ensure SOPS is installed correctly
      command: sops --version
      register: sops_version
      changed_when: false
    - name: Show SOPS version
      debug:
        msg: "{{ sops_version.stdout }}"
