- name: Pre-commits, Terraform
  hosts: localhost
  become: true
  tasks:
    - name: Gather OS family
      ansible.builtin.setup:
        filter: ansible_os_family
      register: os_info
    - name: Download HashiCorp GPG key for Debian-based systems
      get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.gpg
        mode: '0644'
      when: os_info.ansible_facts.ansible_os_family == "Debian"
    - name: Ensure /etc/apt/sources.list.d exists
      file:
        path: /etc/apt/sources.list.d
        state: directory
        mode: '0755'
      when: os_info.ansible_facts.ansible_os_family == "Debian"
    - name: Ensure /etc/apt/sources.list.d directory exists
      file:
        path: /etc/apt/sources.list.d
        state: directory
        mode: '0755'
    - name: Ensure HashiCorp repository file exists
      file:
        path: /etc/apt/sources.list.d/hashicorp.list
        state: touch
        mode: '0644'
    - name: Add HashiCorp Repository for Debian-based systems
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/hashicorp.list
        line: |
          deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
      when: os_info.ansible_facts.ansible_os_family == "Debian"
    - name: Update package cache for Debian-based systems
      apt:
        update_cache: yes
      when: os_info.ansible_facts.ansible_os_family == "Debian"
    - name: Install dnf config-manager for Fedora-based systems
      package:
        name: dnf-plugins-core
        state: present
      when: os_info.ansible_facts.ansible_os_family == "RedHat"
    - name: Add HashiCorp Repository for Fedora-based systems
      copy:
        dest: /etc/yum.repos.d/hashicorp.repo
        content: |
          [hashicorp]
          name=HashiCorp Stable - $basearch
          baseurl=https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
          enabled=1
          gpgcheck=1
          gpgkey=https://rpm.releases.hashicorp.com/gpg
      when: os_info.ansible_facts.ansible_os_family == "RedHat"
    - name: Install Terraform for Debian-based systems
      apt:
        name: terraform
        state: latest
      when: os_info.ansible_facts.ansible_os_family == "Debian"
      tags:
        - terraform
    - name: Install Terraform for Fedora-based systems
      dnf:
        name: terraform
        state: latest
      when: os_info.ansible_facts.ansible_os_family == "RedHat"
    - name: Verify Terraform installation
      shell: terraform -help
      register: terraform_help
      changed_when: false
    - name: Configure Autocomplete
      shell: terraform -install-autocomplete
    - name: Print verification output
      debug:
        var: terraform_help.stdout
