#!/bin/bash
# VERY IMPORTANT: THIS Will only be triggered with GIT tracked files.
# This is to be used by git-secrets. It creates patterns that will trigger it.
# Common secret keys with case-insensitivity and various separators
echo 'SECRET[_-]?KEY ?[=:].*|secret[_-]?key ?[=:].*'
echo 'API[_-]?KEY ?[=:].*|api[_-]?key ?[=:].*'
echo 'ACCESS[_-]?TOKEN ?[=:].*|access[_-]?token ?[=:].*'
echo 'AUTH[_-]?TOKEN ?[=:].*|auth[_-]?token ?[=:].*'

# Database credentials
echo 'DB[_-]?USERNAME ?[=:].*|db[_-]?username ?[=:].*'
echo 'DB[_-]?PASSWORD ?[=:].*|db[_-]?password ?[=:].*'

# OAuth tokens
echo 'OAUTH[_-]?ACCESS[_-]?TOKEN ?[=:].*|oauth[_-]?access[_-]?token ?[=:].*'
echo 'OAUTH[_-]?REFRESH[_-]?TOKEN ?[=:].*|oauth[_-]?refresh[_-]?token ?[=:].*'

# Private keys
echo 'RSA[_-]?PRIVATE[_-]?KEY ?[=:].*|rsa[_-]?private[_-]?key ?[=:].*'
echo 'SSH[_-]?PRIVATE[_-]?KEY ?[=:].*|ssh[_-]?private[_-]?key ?[=:].*'

# Miscellaneous
echo 'PASSWORD ?[=:].*|password ?[=:].*'
echo 'PASSPHRASE ?[=:].*|passphrase ?[=:].*'
echo 'ENCRYPTION[_-]?KEY ?[=:].*|encryption[_-]?key ?[=:].*'
echo 'CLIENT[_-]?SECRET ?[=:].*|client[_-]?secret ?[=:].*'
echo 'CLIENT[_-]?ID ?[=:].*|client[_-]?id ?[=:].*'

# API Keys
echo 'API[_-]?SECRET ?[=:].*|api[_-]?secret ?[=:].*'
echo 'API[_-]?KEY ?[=:].*|api[_-]?key ?[=:].*'
echo 'GITHUB[_-]?TOKEN ?[=:].*|github[_-]?token ?[=:].*'
echo 'GITLAB[_-]?TOKEN ?[=:].*|gitlab[_-]?token ?[=:].*'
echo 'BITBUCKET[_-]?TOKEN ?[=:].*|bitbucket[_-]?token ?[=:].*'
# Database
echo 'DB[_-]?HOST ?[=:].*|db[_-]?host ?[=:].*'
echo 'DB[_-]?PORT ?[=:].*|db[_-]?port ?[=:].*'
echo 'DB[_-]?NAME ?[=:].*|db[_-]?name ?[=:].*'
echo 'DB[_-]?USER ?[=:].*|db[_-]?user ?[=:].*'
echo 'DB[_-]?PASS ?[=:].*|db[_-]?pass ?[=:].*'
echo 'DATABASE[_-]?URL ?[=:].*|database[_-]?url ?[=:].*'

# Authentication Tokens
echo 'JWT[_-]?SECRET ?[=:].*|jwt[_-]?secret ?[=:].*'
echo 'SESSION[_-]?SECRET ?[=:].*|session[_-]?secret ?[=:].*'
echo 'AUTH[_-]?KEY ?[=:].*|auth[_-]?key ?[=:].*'
echo 'BEARER[_-]?TOKEN ?[=:].*|bearer[_-]?token ?[=:].*'

# Encryption Keys
echo 'RSA[_-]?KEY ?[=:].*|rsa[_-]?key ?[=:].*'
echo 'DSA[_-]?KEY ?[=:].*|dsa[_-]?key ?[=:].*'
echo 'EC[_-]?KEY ?[=:].*|ec[_-]?key ?[=:].*'
echo 'ENCRYPT[_-]?KEY ?[=:].*|encrypt[_-]?key ?[=:].*'
echo 'SYMMETRIC[_-]?KEY ?[=:].*|symmetric[_-]?key ?[=:].*'

# Cloud Providers
echo 'AZURE[_-]?SECRET ?[=:].*|azure[_-]?secret ?[=:].*'
echo 'GCP[_-]?KEY ?[=:].*|gcp[_-]?key ?[=:].*'
echo 'GCP[_-]?SECRET ?[=:].*|gcp[_-]?secret ?[=:].*'
echo 'GCS[_-]?KEY ?[=:].*|gcs[_-]?key ?[=:].*'
echo 'S3[_-]?SECRET ?[=:].*|s3[_-]?secret ?[=:].*'
echo 'DO[_-]?SPACES[_-]?KEY ?[=:].*|do[_-]?spaces[_-]?key ?[=:].*'

# Certificates
echo 'CERTIFICATE ?[=:].*|certificate ?[=:].*'
echo 'PRIVATE[_-]?KEY ?[=:].*|private[_-]?key ?[=:].*'
echo 'PUBLIC[_-]?KEY ?[=:].*|public[_-]?key ?[=:].*'
echo 'SSH[_-]?KEY ?[=:].*|ssh[_-]?key ?[=:].*'

# Service Accounts
echo 'SERVICE[_-]?ACCOUNT ?[=:].*|service[_-]?account ?[=:].*'
echo 'ACCOUNT[_-]?ID ?[=:].*|account[_-]?id ?[=:].*'
echo 'ACCOUNT[_-]?KEY ?[=:].*|account[_-]?key ?[=:].*'

# Miscellaneous Secrets
echo 'ACCESS[_-]?KEY ?[=:].*|access[_-]?key ?[=:].*'
echo 'ACCESS[_-]?SECRET ?[=:].*|access[_-]?secret ?[=:].*'
echo 'CONSUMER[_-]?KEY ?[=:].*|consumer[_-]?key ?[=:].*'
echo 'CONSUMER[_-]?SECRET ?[=:].*|consumer[_-]?secret ?[=:].*'
echo 'SSH[_-]?PASSPHRASE ?[=:].*|ssh[_-]?passphrase ?[=:].*'
echo 'MASTER[_-]?KEY ?[=:].*|master[_-]?key ?[=:].*'
echo 'SSH[_-]?TUNNEL ?[=:].*|ssh[_-]?tunnel ?[=:].*'
echo 'VPN[_-]?KEY ?[=:].*|vpn[_-]?key ?[=:].*'
echo 'FTP[_-]?PASSWORD ?[=:].*|ftp[_-]?password ?[=:].*'
echo 'SMTP[_-]?PASSWORD ?[=:].*|smtp[_-]?password ?[=:].*'
# Cloud Configuration
echo 'CLOUDFLARE[_-]?API[_-]?KEY ?[=:].*|cloudflare[_-]?api[_-]?key ?[=:].*'
echo 'HEROKU[_-]?API[_-]?KEY ?[=:].*|heroku[_-]?api[_-]?key ?[=:].*'
echo 'AZURE[_-]?STORAGE[_-]?KEY ?[=:].*|azure[_-]?storage[_-]?key ?[=:].*'
echo 'DIGITALOCEAN[_-]?TOKEN ?[=:].*|digitalocean[_-]?token ?[=:].*'
echo 'ORACLE[_-]?CLOUD[_-]?IDENTIFIER ?[=:].*|oracle[_-]?cloud[_-]?identifier ?[=:].*'
echo 'IBM[_-]?CLOUD[_-]?API[_-]?KEY ?[=:].*|ibm[_-]?cloud[_-]?api[_-]?key ?[=:].*'

# Deployment Keys
echo 'DEPLOY[_-]?KEY ?[=:].*|deploy[_-]?key ?[=:].*'
echo 'DEPLOYMENT[_-]?TOKEN ?[=:].*|deployment[_-]?token ?[=:].*'
echo 'CONTAINER[_-]?REGISTRY[_-]?KEY ?[=:].*|container[_-]?registry[_-]?key ?[=:].*'
echo 'DOCKER[_-]?CONFIG ?[=:].*|docker[_-]?config ?[=:].*'
echo 'KUBERNETES[_-]?SECRET ?[=:].*|kubernetes[_-]?secret ?[=:].*'
echo 'HELM[_-]?SECRET ?[=:].*|helm[_-]?secret ?[=:].*'

# Networking
echo 'SSL[_-]?CERTIFICATE ?[=:].*|ssl[_-]?certificate ?[=:].*'
echo 'SSL[_-]?PRIVATE[_-]?KEY ?[=:].*|ssl[_-]?private[_-]?key ?[=:].*'
echo 'API[_-]?ENDPOINT ?[=:].*|api[_-]?endpoint ?[=:].*'
echo 'ROUTING[_-]?KEY ?[=:].*|routing[_-]?key ?[=:].*'
echo 'NETWORK[_-]?ACCESS[_-]?TOKEN ?[=:].*|network[_-]?access[_-]?token ?[=:].*'
echo 'PROXY[_-]?URL ?[=:].*|proxy[_-]?url ?[=:].*'

# Application Keys
echo 'APP[_-]?SECRET[_-]?KEY ?[=:].*|app[_-]?secret[_-]?key ?[=:].*'
echo 'APP[_-]?ENCRYPTION[_-]?KEY ?[=:].*|app[_-]?encryption[_-]?key ?[=:].*'
echo 'APPLICATION[_-]?CREDENTIALS ?[=:].*|application[_-]?credentials ?[=:].*'
echo 'WEBHOOK[_-]?SECRET ?[=:].*|webhook[_-]?secret ?[=:].*'
echo 'CSRF[_-]?TOKEN ?[=:].*|csrf[_-]?token ?[=:].*'
echo 'CSRF[_-]?SECRET ?[=:].*|csrf[_-]?secret ?[=:].*'

# Monitoring and Logging
echo 'LOGGLY[_-]?TOKEN ?[=:].*|loggly[_-]?token ?[=:].*'
echo 'PAPERTRAIL[_-]?API[_-]?TOKEN ?[=:].*|papertrail[_-]?api[_-]?token ?[=:].*'
echo 'DATADOG[_-]?API[_-]?KEY ?[=:].*|datadog[_-]?api[_-]?key ?[=:].*'
echo 'NEW[_-]?RELIC[_-]?LICENSE[_-]?KEY ?[=:].*|new[_-]?relic[_-]?license[_-]?key ?[=:].*'
echo 'SENTRY[_-]?DSN ?[=:].*|sentry[_-]?dsn ?[=:].*'
echo 'GRAYLOG[_-]?PASSWORD ?[=:].*|graylog[_-]?password ?[=:].*'
# Messaging and Communication
echo 'SLACK[_-]?TOKEN ?[=:].*|slack[_-]?token ?[=:].*'
echo 'SLACK[_-]?WEBHOOK[_-]?URL ?[=:].*|slack[_-]?webhook[_-]?url ?[=:].*'
echo 'TWILIO[_-]?ACCOUNT[_-]?SID ?[=:].*|twilio[_-]?account[_-]?sid ?[=:].*'
echo 'TWILIO[_-]?AUTH[_-]?TOKEN ?[=:].*|twilio[_-]?auth[_-]?token ?[=:].*'
echo 'SENDGRID[_-]?API[_-]?KEY ?[=:].*|sendgrid[_-]?api[_-]?key ?[=:].*'
echo 'MAILGUN[_-]?API[_-]?KEY ?[=:].*|mailgun[_-]?api[_-]?key ?[=:].*'

# DevOps Tools
echo 'TERRAFORM[_-]?BACKEND[_-]?CONFIG ?[=:].*|terraform[_-]?backend[_-]?config ?[=:].*'
echo 'ANSIBLE[_-]?VAULT[_-]?PASSWORD ?[=:].*|ansible[_-]?vault[_-]?password ?[=:].*'
echo 'JENKINS[_-]?SECRET[_-]?TOKEN ?[=:].*|jenkins[_-]?secret[_-]?token ?[=:].*'
echo 'TRAVIS[_-]?CI[_-]?SECRET ?[=:].*|travis[_-]?ci[_-]?secret ?[=:].*'
echo 'CIRCLECI[_-]?TOKEN ?[=:].*|circleci[_-]?token ?[=:].*'
echo 'GITLAB[_-]?CI[_-]?SECRET ?[=:].*|gitlab[_-]?ci[_-]?secret ?[=:].*'

# Miscellaneous Configuration
echo 'NGINX[_-]?AUTH[_-]?BASIC ?[=:].*|nginx[_-]?auth[_-]?basic ?[=:].*'
echo 'HTACCESS[_-]?PASSWORD ?[=:].*|htaccess[_-]?password ?[=:].*'
echo 'REDIS[_-]?PASSWORD ?[=:].*|redis[_-]?password ?[=:].*'
echo 'RABBITMQ[_-]?DEFAULT[_-]?PASS ?[=:].*|rabbitmq[_-]?default[_-]?pass ?[=:].*'
echo 'MYSQL[_-]?ROOT[_-]?PASSWORD ?[=:].*|mysql[_-]?root[_-]?password ?[=:].*'
echo 'POSTGRES[_-]?PASSWORD ?[=:].*|postgres[_-]?password ?[=:].*'

# Build and CI/CD
echo 'BUILD[_-]?SECRET ?[=:].*|build[_-]?secret ?[=:].*'
echo 'CI[_-]?DEPLOY[_-]?PASSWORD ?[=:].*|ci[_-]?deploy[_-]?password ?[=:].*'
echo 'ARTIFACTORY[_-]?API[_-]?KEY ?[=:].*|artifactory[_-]?api[_-]?key ?[=:].*'
echo 'BAZEL[_-]?CACHE[_-]?KEY ?[=:].*|bazel[_-]?cache[_-]?key ?[=:].*'
echo 'BUILDKITE[_-]?TOKEN ?[=:].*|buildkite[_-]?token ?[=:].*'

# Version Control
echo 'GIT[_-]?PASSWORD ?[=:].*|git[_-]?password ?[=:].*'
echo 'REPO[_-]?ACCESS[_-]?TOKEN ?[=:].*|repo[_-]?access[_-]?token ?[=:].*'
echo 'SVN[_-]?CREDENTIALS ?[=:].*|svn[_-]?credentials ?[=:].*'
echo 'MERGE[_-]?REQUEST[_-]?TOKEN ?[=:].*|merge[_-]?request[_-]?token ?[=:].*'
echo 'RELEASE[_-]?KEY ?[=:].*|release[_-]?key ?[=:].*'

# Cloud Management
echo 'SCALEWAY[_-]?API[_-]?KEY ?[=:].*|scaleway[_-]?api[_-]?key ?[=:].*'
echo 'CLOUDFORMATION[_-]?SECRET ?[=:].*|cloudformation[_-]?secret ?[=:].*'
echo 'OPENSTACK[_-]?ADMIN[_-]?PASSWORD ?[=:].*|openstack[_-]?admin[_-]?password ?[=:].*'
echo 'VULTR[_-]?API[_-]?KEY ?[=:].*|vultr[_-]?api[_-]?key ?[=:].*'
echo 'LINODE[_-]?API[_-]?KEY ?[=:].*|linode[_-]?api[_-]?key ?[=:].*'

# Containerization
echo 'DOCKERHUB[_-]?TOKEN ?[=:].*|dockerhub[_-]?token ?[=:].*'
echo 'CONTAINER[_-]?SECRET ?[=:].*|container[_-]?secret ?[=:].*'
echo 'PODMAN[_-]?KEY ?[=:].*|podman[_-]?key ?[=:].*'
echo 'K8S[_-]?ADMIN[_-]?PASSWORD ?[=:].*|k8s[_-]?admin[_-]?password ?[=:].*'
echo 'HELM[_-]?CHART[_-]?SECRET ?[=:].*|helm[_-]?chart[_-]?secret ?[=:].*'

# Security and Compliance
echo 'SECURITY[_-]?AUDIT[_-]?KEY ?[=:].*|security[_-]?audit[_-]?key ?[=:].*'
echo 'VAULT[_-]?TOKEN ?[=:].*|vault[_-]?token ?[=:].*'
echo 'ENCRYPTION[_-]?CERT ?[=:].*|encryption[_-]?cert ?[=:].*'
echo 'FIREWALL[_-]?ACCESS[_-]?KEY ?[=:].*|firewall[_-]?access[_-]?key ?[=:].*'
echo 'INTRUSION[_-]?DETECTION[_-]?KEY ?[=:].*|intrusion[_-]?detection[_-]?key ?[=:].*'

# Network Configuration
echo 'VPN[_-]?SECRET ?[=:].*|vpn[_-]?secret ?[=:].*'
echo 'API[_-]?GATEWAY[_-]?KEY ?[=:].*|api[_-]?gateway[_-]?key ?[=:].*'
echo 'LOAD[_-]?BALANCER[_-]?TOKEN ?[=:].*|load[_-]?balancer[_-]?token ?[=:].*'
echo 'PROXY[_-]?AUTHENTICATION ?[=:].*|proxy[_-]?authentication ?[=:].*'
echo 'DNS[_-]?MANAGEMENT[_-]?KEY ?[=:].*|dns[_-]?management[_-]?key ?[=:].*'

# Platform Specific
echo 'HEROKU[_-]?DEPLOY[_-]?SECRET ?[=:].*|heroku[_-]?deploy[_-]?secret ?[=:].*'
echo 'AZURE[_-]?TENANT[_-]?ID ?[=:].*|azure[_-]?tenant[_-]?id ?[=:].*'
echo 'GCP[_-]?PROJECT[_-]?ID ?[=:].*|gcp[_-]?project[_-]?id ?[=:].*'
echo 'AWS[_-]?ELB[_-]?KEY ?[=:].*|aws[_-]?elb[_-]?key ?[=:].*'
echo 'IBM[_-]?SYSPLEX[_-]?TOKEN ?[=:].*|ibm[_-]?sysplex[_-]?token ?[=:].*'

# Third-Party Services
echo 'STRIPE[_-]?API[_-]?KEY ?[=:].*|stripe[_-]?api[_-]?key ?[=:].*'
echo 'PAYPAL[_-]?CLIENT[_-]?SECRET ?[=:].*|paypal[_-]?client[_-]?secret ?[=:].*'
echo 'BRAINTREE[_-]?ACCESS[_-]?KEY ?[=:].*|braintree[_-]?access[_-]?key ?[=:].*'
echo 'SHOPIFY[_-]?SECRET ?[=:].*|shopify[_-]?secret ?[=:].*'
echo 'ZENDESK[_-]?API[_-]?TOKEN ?[=:].*|zendesk[_-]?api[_-]?token ?[=:].*'

# Messaging and Queues
echo 'KAFKA[_-]?SECRET ?[=:].*|kafka[_-]?secret ?[=:].*'
echo 'RABBITMQ[_-]?API[_-]?KEY ?[=:].*|rabbitmq[_-]?api[_-]?key ?[=:].*'
echo 'ACTIVEMQ[_-]?USER ?[=:].*|activemq[_-]?user ?[=:].*'
echo 'SQS[_-]?SECRET[_-]?KEY ?[=:].*|sqs[_-]?secret[_-]?key ?[=:].*'
echo 'PUBSUB[_-]?ACCESS[_-]?TOKEN ?[=:].*|pubsub[_-]?access[_-]?token ?[=:].*'

# Monitoring and Observability
echo 'PROMETHEUS[_-]?SECRET ?[=:].*|prometheus[_-]?secret ?[=:].*'
echo 'GRAFANA[_-]?API[_-]?KEY ?[=:].*|grafana[_-]?api[_-]?key ?[=:].*'
echo 'SPLUNK[_-]?ACCESS[_-]?TOKEN ?[=:].*|splunk[_-]?access[_-]?token ?[=:].*'
echo 'ELASTICSEARCH[_-]?PASSWORD ?[=:].*|elasticsearch[_-]?password ?[=:].*'
echo 'ZABBIX[_-]?HOST[_-]?KEY ?[=:].*|zabbix[_-]?host[_-]?key ?[=:].*'

#!/bin/bash

# AWS-specific secret terms
echo 'AWS[_-]?ACCESS[_-]?KEY[_-]?ID ?[=:].*|aws[_-]?access[_-]?key[_-]?id ?[=:].*'
echo 'AWS[_-]?SECRET[_-]?ACCESS[_-]?KEY ?[=:].*|aws[_-]?secret[_-]?access[_-]?key ?[=:].*'
echo 'AWS[_-]?SESSION[_-]?TOKEN ?[=:].*|aws[_-]?session[_-]?token ?[=:].*'
echo 'AWS[_-]?SECURITY[_-]?TOKEN ?[=:].*|aws[_-]?security[_-]?token ?[=:].*'
echo 'AWS[_-]?CREDENTIAL[_-]?FILE ?[=:].*|aws[_-]?credential[_-]?file ?[=:].*'
echo 'AWS[_-]?CONFIG[_-]?FILE ?[=:].*|aws[_-]?config[_-]?file ?[=:].*'
echo 'AWS[_-]?SECRET[_-]?KEY ?[=:].*|aws[_-]?secret[_-]?key ?[=:].*'
echo 'AWS[_-]?SERVICE[_-]?KEY ?[=:].*|aws[_-]?service[_-]?key ?[=:].*'
echo 'AWS[_-]?ELASTIC[_-]?BEANSTALK[_-]?SECRET ?[=:].*|aws[_-]?elastic[_-]?beanstalk[_-]?secret ?[=:].*'
echo 'AWS[_-]?S3[_-]?SECRET ?[=:].*|aws[_-]?s3[_-]?secret ?[=:].*'
echo 'AWS[_-]?RDS[_-]?PASSWORD ?[=:].*|aws[_-]?rds[_-]?password ?[=:].*'
echo 'AWS[_-]?IAM[_-]?USER[_-]?SECRET ?[=:].*|aws[_-]?iam[_-]?user[_-]?secret ?[=:].*'
echo 'AWS[_-]?ROOT[_-]?KEY ?[=:].*|aws[_-]?root[_-]?key ?[=:].*'
echo 'AWS[_-]?SECRET[_-]?BUNDLE ?[=:].*|aws[_-]?secret[_-]?bundle ?[=:].*'
echo 'AWS[_-]?EC2[_-]?SECRET ?[=:].*|aws[_-]?ec2[_-]?secret ?[=:].*'
echo 'AWS[_-]?GLUE[_-]?PASSWORD ?[=:].*|aws[_-]?glue[_-]?password ?[=:].*'
echo 'AWS[_-]?DYNAMODB[_-]?SECRET ?[=:].*|aws[_-]?dynamodb[_-]?secret ?[=:].*'
echo 'AWS[_-]?LAMBDA[_-]?SECRET ?[=:].*|aws[_-]?lambda[_-]?secret ?[=:].*'
echo 'AWS[_-]?API[_-]?GATEWAY[_-]?KEY ?[=:].*|aws[_-]?api[_-]?gateway[_-]?key ?[=:].*'
echo 'AWS[_-]?KMS[_-]?SECRET ?[=:].*|aws[_-]?kms[_-]?secret ?[=:].*'
echo 'AWS[_-]?SES[_-]?PASSWORD ?[=:].*|aws[_-]?ses[_-]?password ?[=:].*'
echo 'AWS[_-]?CLOUDFRONT[_-]?KEY ?[=:].*|aws[_-]?cloudfront[_-]?key ?[=:].*'
echo 'AWS[_-]?ROUTE[_-]?53[_-]?SECRET ?[=:].*|aws[_-]?route[_-]?53[_-]?secret ?[=:].*'
echo 'AWS[_-]?ECS[_-]?SECRET ?[=:].*|aws[_-]?ecs[_-]?secret ?[=:].*'
echo 'AWS[_-]?EKS[_-]?SECRET ?[=:].*|aws[_-]?eks[_-]?secret ?[=:].*'
echo 'AWS[_-]?REDSHIFT[_-]?PASSWORD ?[=:].*|aws[_-]?redshift[_-]?password ?[=:].*'
echo 'AWS[_-]?MQ[_-]?BROKER[_-]?SECRET ?[=:].*|aws[_-]?mq[_-]?broker[_-]?secret ?[=:].*'
echo 'AWS[_-]?DATASYNC[_-]?SECRET ?[=:].*|aws[_-]?datasync[_-]?secret ?[=:].*'
echo 'AWS[_-]?CODEBUILD[_-]?SECRET ?[=:].*|aws[_-]?codebuild[_-]?secret ?[=:].*'
echo 'AWS[_-]?CODECOMMIT[_-]?TOKEN ?[=:].*|aws[_-]?codecommit[_-]?token ?[=:].*'
echo 'AWS[_-]?CODEDEPLOY[_-]?KEY ?[=:].*|aws[_-]?codedeploy[_-]?key ?[=:].*'
echo 'AWS[_-]?CODEPIPELINE[_-]?SECRET ?[=:].*|aws[_-]?codepipeline[_-]?secret ?[=:].*'
echo 'AWS[_-]?DIRECTCONNECT[_-]?KEY ?[=:].*|aws[_-]?directconnect[_-]?key ?[=:].*'
echo 'AWS[_-]?ELASTICACHE[_-]?PASSWORD ?[=:].*|aws[_-]?elasticache[_-]?password ?[=:].*'
echo 'AWS[_-]?FARGATE[_-]?SECRET ?[=:].*|aws[_-]?fargate[_-]?secret ?[=:].*'
echo 'AWS[_-]?LIGHTSAIL[_-]?SECRET ?[=:].*|aws[_-]?lightsail[_-]?secret ?[=:].*'
echo 'AWS[_-]?QUICKSIGHT[_-]?USER[_-]?SECRET ?[=:].*|aws[_-]?quicksight[_-]?user[_-]?secret ?[=:].*'
echo 'AWS[_-]?SAGEMAKER[_-]?KEY ?[=:].*|aws[_-]?sagemaker[_-]?key ?[=:].*'
echo 'AWS[_-]?SNOWBALL[_-]?SECRET ?[=:].*|aws[_-]?snowball[_-]?secret ?[=:].*'
echo 'AWS[_-]?SQS[_-]?SECRET ?[=:].*|aws[_-]?sqs[_-]?secret ?[=:].*'
echo 'AWS[_-]?SWF[_-]?TOKEN ?[=:].*|aws[_-]?swf[_-]?token ?[=:].*'
echo 'AWS[_-]?TRANSIT[_-]?GATEWAY[_-]?SECRET ?[=:].*|aws[_-]?transit[_-]?gateway[_-]?secret ?[=:].*'
echo 'AWS[_-]?VPC[_-]?ENDPOINT[_-]?SECRET ?[=:].*|aws[_-]?vpc[_-]?endpoint[_-]?secret ?[=:].*'
echo 'AWS[_-]?WAF[_-]?SECRET ?[=:].*|aws[_-]?waf[_-]?secret ?[=:].*'
echo 'AWS[_-]?WORKMAIL[_-]?SECRET ?[=:].*|aws[_-]?workmail[_-]?secret ?[=:].*'
echo 'AWS[_-]?WORKSPACES[_-]?SECRET ?[=:].*|aws[_-]?workspaces[_-]?secret ?[=:].*'
echo 'AWS[_-]?XRAY[_-]?SECRET ?[=:].*|aws[_-]?xray[_-]?secret ?[=:].*'
echo 'AWS[_-]?MEDIASTORE[_-]?SECRET ?[=:].*|aws[_-]?mediastore[_-]?secret ?[=:].*'
echo 'AWS[_-]?MEDIACONVERT[_-]?KEY ?[=:].*|aws[_-]?mediaconvert[_-]?key ?[=:].*'
echo 'AWS[_-]?MEDIA[_-]?LIVE[_-]?SECRET ?[=:].*|aws[_-]?media[_-]?live[_-]?secret ?[=:].*'
echo 'AWS[_-]?MEDIAPACKAGE[_-]?SECRET ?[=:].*|aws[_-]?mediapackage[_-]?secret ?[=:].*'
echo 'AWS[_-]?MEDIA[_-]?TAILOR[_-]?SECRET ?[=:].*|aws[_-]?media[_-]?tailor[_-]?secret ?[=:].*'
echo 'AWS[_-]?APP[_-]?RUNNER[_-]?SECRET ?[=:].*|aws[_-]?app[_-]?runner[_-]?secret ?[=:].*'
echo 'AWS[_-]?APP[_-]?FLOW[_-]?SECRET ?[=:].*|aws[_-]?app[_-]?flow[_-]?secret ?[=:].*'
echo 'AWS[_-]?APP[_-]?INTEGRATIONS[_-]?SECRET ?[=:].*|aws[_-]?app[_-]?integrations[_-]?secret ?[=:].*'
echo 'AWS[_-]?APP[_-]?MESH[_-]?SECRET ?[=:].*|aws[_-]?app[_-]?mesh[_-]?secret ?[=:].*'
echo 'AWS[_-]?BACKUP[_-]?SECRET ?[=:].*|aws[_-]?backup[_-]?secret ?[=:].*'
echo 'AWS[_-]?BATCH[_-]?SECRET ?[=:].*|aws[_-]?batch[_-]?secret ?[=:].*'
echo 'AWS[_-]?BRAKET[_-]?SECRET ?[=:].*|aws[_-]?braket[_-]?secret ?[=:].*'
echo 'AWS[_-]?CHIME[_-]?SECRET ?[=:].*|aws[_-]?chime[_-]?secret ?[=:].*'
echo 'AWS[_-]?CLOUD9[_-]?SECRET ?[=:].*|aws[_-]?cloud9[_-]?secret ?[=:].*'
echo 'AWS[_-]?CLOUDFORMATION[_-]?SECRET ?[=:].*|aws[_-]?cloudformation[_-]?secret ?[=:].*'
echo 'AWS[_-]?CLOUDDIRECTORY[_-]?SECRET ?[=:].*|aws[_-]?clouddirectory[_-]?secret ?[=:].*'
echo 'AWS[_-]?CLOUDFRONT[_-]?SECRET ?[=:].*|aws[_-]?cloudfront[_-]?secret ?[=:].*'
echo 'AWS[_-]?CLOUDSEARCH[_-]?SECRET ?[=:].*|aws[_-]?cloudsearch[_-]?secret ?[=:].*'
##newly added items
# Additional secret patterns
echo 'SECRET[_-]?TOKEN ?[=:].*|secret[_-]?token ?[=:].*'
echo 'SECRET[_-]?ACCESS[_-]?KEY ?[=:].*|secret[_-]?access[_-]?key ?[=:].*'
echo 'ACCESS[_-]?ID ?[=:].*|access[_-]?id ?[=:].*'
echo 'PRIVATE[_-]?SECRET[_-]?KEY ?[=:].*|private[_-]?secret[_-]?key ?[=:].*'
echo 'JWT[_-]?KEY ?[=:].*|jwt[_-]?key ?[=:].*'
echo 'SECURITY[_-]?TOKEN ?[=:].*|security[_-]?token ?[=:].*'
echo 'AUTH[_-]?CODE ?[=:].*|auth[_-]?code ?[=:].*'
echo 'ACCESS[_-]?CREDENTIAL ?[=:].*|access[_-]?credential ?[=:].*'
echo 'MASTER[_-]?PASSWORD ?[=:].*|master[_-]?password ?[=:].*'
echo 'ROOT[_-]?SECRET[_-]?KEY ?[=:].*|root[_-]?secret[_-]?key ?[=:].*'
echo 'GLOBAL[_-]?TOKEN ?[=:].*|global[_-]?token ?[=:].*'
echo 'SUPER[_-]?USER[_-]?PASSWORD ?[=:].*|super[_-]?user[_-]?password ?[=:].*'
echo 'USER[_-]?PRIVATE[_-]?KEY ?[=:].*|user[_-]?private[_-]?key ?[=:].*'
echo 'SECRET[_-]?ENCRYPTION[_-]?KEY ?[=:].*|secret[_-]?encryption[_-]?key ?[=:].*'
echo 'HMAC[_-]?KEY ?[=:].*|hmac[_-]?key ?[=:].*'
echo 'SERVICE[_-]?TOKEN ?[=:].*|service[_-]?token ?[=:].*'
echo 'SERVICE[_-]?API[_-]?KEY ?[=:].*|service[_-]?api[_-]?key ?[=:].*'
echo 'CREDENTIAL[_-]?SECRET ?[=:].*|credential[_-]?secret ?[=:].*'
echo 'ENCRYPTED[_-]?SECRET ?[=:].*|encrypted[_-]?secret ?[=:].*'
echo 'VAULT[_-]?ACCESS[_-]?TOKEN ?[=:].*|vault[_-]?access[_-]?token ?[=:].*'
echo 'CREDENTIALS[_-]?FILE ?[=:].*|credentials[_-]?file ?[=:].*'
echo 'AUTH[_-]?SECRET ?[=:].*|auth[_-]?secret ?[=:].*'
echo 'AUTHENTICATION[_-]?KEY ?[=:].*|authentication[_-]?key ?[=:].*'
echo 'OAUTH[_-]?KEY ?[=:].*|oauth[_-]?key ?[=:].*'
echo 'TOKEN[_-]?SECRET ?[=:].*|token[_-]?secret ?[=:].*'
echo 'SECRET[_-]?AUTHENTICATION[_-]?TOKEN ?[=:].*|secret[_-]?authentication[_-]?token ?[=:].*'
echo 'REGISTRY[_-]?TOKEN ?[=:].*|registry[_-]?token ?[=:].*'
echo 'DATABASE[_-]?SECRET ?[=:].*|database[_-]?secret ?[=:].*'
echo 'REDIS[_-]?SECRET ?[=:].*|redis[_-]?secret ?[=:].*'
echo 'MYSQL[_-]?SECRET ?[=:].*|mysql[_-]?secret ?[=:].*'
echo 'DATABASE[_-]?PASSWORD ?[=:].*|database[_-]?password ?[=:].*'
echo 'DB[_-]?SECRET[_-]?TOKEN ?[=:].*|db[_-]?secret[_-]?token ?[=:].*'
echo 'AWS[_-]?DB[_-]?PASSWORD ?[=:].*|aws[_-]?db[_-]?password ?[=:].*'
echo 'CLOUD[_-]?SECRET ?[=:].*|cloud[_-]?secret ?[=:].*'
echo 'AWS[_-]?AUTH[_-]?KEY ?[=:].*|aws[_-]?auth[_-]?key ?[=:].*'
echo 'GIT[_-]?SECRET ?[=:].*|git[_-]?secret ?[=:].*'
echo 'DEPLOY[_-]?SECRET[_-]?TOKEN ?[=:].*|deploy[_-]?secret[_-]?token ?[=:].*'
echo 'DEPLOYMENT[_-]?CREDENTIALS ?[=:].*|deployment[_-]?credentials ?[=:].*'
echo 'BUILD[_-]?CREDENTIALS ?[=:].*|build[_-]?credentials ?[=:].*'
echo 'BUILD[_-]?TOKEN ?[=:].*|build[_-]?token ?[=:].*'
echo 'KEY[_-]?SECRET ?[=:].*|key[_-]?secret ?[=:].*'
echo 'API[_-]?AUTH[_-]?KEY ?[=:].*|api[_-]?auth[_-]?key ?[=:].*'
echo 'API[_-]?KEY[_-]?SECRET ?[=:].*|api[_-]?key[_-]?secret ?[=:].*'
echo 'SERVER[_-]?KEY ?[=:].*|server[_-]?key ?[=:].*'
echo 'SERVER[_-]?SECRET ?[=:].*|server[_-]?secret ?[=:].*'
echo 'SERVICE[_-]?ACCOUNT[_-]?KEY ?[=:].*|service[_-]?account[_-]?key ?[=:].*'
echo 'K8S[_-]?TOKEN ?[=:].*|k8s[_-]?token ?[=:].*'
echo 'K8S[_-]?SECRET[_-]?KEY ?[=:].*|k8s[_-]?secret[_-]?key ?[=:].*'
echo 'KUBERNETES[_-]?SERVICE[_-]?TOKEN ?[=:].*|kubernetes[_-]?service[_-]?token ?[=:].*'
echo 'KUBERNETES[_-]?PRIVATE[_-]?KEY ?[=:].*|kubernetes[_-]?private[_-]?key ?[=:].*'
echo 'KUBERNETES[_-]?CONFIG ?[=:].*|kubernetes[_-]?config ?[=:].*'
echo 'DOCKER[_-]?PRIVATE[_-]?KEY ?[=:].*|docker[_-]?private[_-]?key ?[=:].*'
echo 'DOCKER[_-]?SECRET[_-]?KEY ?[=:].*|docker[_-]?secret[_-]?key ?[=:].*'
echo 'DOCKER[_-]?TOKEN ?[=:].*|docker[_-]?token ?[=:].*'
echo 'CONTAINER[_-]?SECRET[_-]?TOKEN ?[=:].*|container[_-]?secret[_-]?token ?[=:].*'
echo 'PRIVATE[_-]?CERTIFICATE ?[=:].*|private[_-]?certificate ?[=:].*'
echo 'CERTIFICATE[_-]?SECRET[_-]?KEY ?[=:].*|certificate[_-]?secret[_-]?key ?[=:].*'
echo 'ENCRYPTION[_-]?PASSWORD ?[=:].*|encryption[_-]?password ?[=:].*'
echo 'SYMMETRIC[_-]?PASSWORD ?[=:].*|symmetric[_-]?password ?[=:].*'
echo 'PUBLIC[_-]?AUTH[_-]?KEY ?[=:].*|public[_-]?auth[_-]?key ?[=:].*'
echo 'WEB[_-]?ACCESS[_-]?KEY ?[=:].*|web[_-]?access[_-]?key ?[=:].*'
echo 'LOGIN[_-]?PASSWORD ?[=:].*|login[_-]?password ?[=:].*'
echo 'SSH[_-]?LOGIN[_-]?KEY ?[=:].*|ssh[_-]?login[_-]?key ?[=:].*'
echo 'SSH[_-]?USER[_-]?TOKEN ?[=:].*|ssh[_-]?user[_-]?token ?[=:].*'
echo 'CERT[_-]?LOGIN[_-]?TOKEN ?[=:].*|cert[_-]?login[_-]?token ?[=:].*'
echo 'SERVER[_-]?LOGIN[_-]?KEY ?[=:].*|server[_-]?login[_-]?key ?[=:].*'
echo 'SSH[_-]?CERTIFICATE[_-]?KEY ?[=:].*|ssh[_-]?certificate[_-]?key ?[=:].*'
echo 'CLIENT[_-]?LOGIN[_-]?TOKEN ?[=:].*|client[_-]?login[_-]?token ?[=:].*'
echo 'JWT[_-]?ACCESS[_-]?TOKEN ?[=:].*|jwt[_-]?access[_-]?token ?[=:].*'
