repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: trailing-whitespace
      - id: check-symlinks
      - id: check-xml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: name-tests-test
      - id: pretty-format-json
        args: [--autofix, --indent, "  "]
      - id: requirements-txt-fixer
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        additional_dependencies: ['gibberish-detector']
  - repo: https://github.com/bridgecrewio/checkov
    rev: '2.5.8'
    hooks:
      - id: checkov
        files: \.tf$
        args: ["--quiet"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.2
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
        args: [--py310-plus]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--ignore=E501,W503,E203']
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
        args:
          - --baseline-path=.gitleaks_report.json
          - --verbose
  - repo: https://github.com/gitleaks/gitleaks
    # does nothing unless patterns or providers are added: see readme. Will only be triggered by git-tracked files
    # git secrets --add-provider -- ~/repositories/bitbucket/williseed1/configs/repos-git/.custom_git_secrets_provider.sh
    rev: v8.18.0
    hooks:
      - id: gitleaks
        exclude: ^\.secrets\.baseline$
  - repo: https://github.com/aufdenpunkt/pre-commit-js-beautify
    rev: 1.13.0
    hooks:
      - id: js-beautify
        args: [-r]
        additional_dependencies: ['js-beautify@1.14.7']
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --fail'
        language: system
        stages: ["commit", "push"]
  # will not do anything unless patterns are added: see readme, or just add provider. Will ONLY BE TRIGGERED BY TRACKED files!!!
  # git-secrets --add-provider ~/repositories/bitbucket/williseed1/configs/repos-git/.custom_git_secrets_provider.sh
  - repo: local
    hooks:
      - id: git-secrets
        name: git-secrets
        entry: git secrets --scan
        language: system
        files: '.*'
        exclude: '.custom_git_secrets_provider.sh'
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: infracost_breakdown
        args:
          - --args=--path=terraform/
        verbose: true
      - id: terragrunt_fmt
      - id: terragrunt_validate
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
        ##  You must specify the collections location since it is part of a different virtual environment.  Also, you should  probably not run this pre-commit in any virtual environment, even if it's cancelable, use it's awn ansible lint venv.
        ##  export ANSIBLE_COLLECTIONS_PATH="$HOME/virtual_environments/ansible/lib/python3.10/site-packages/ansible_collections"
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.2.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        entry: ansible-lint
